### ISSUE TITLE
Tech Lady Hackathon - Ship new front end

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#135]
Let's ship the new front end at Tech Lady Hackathon 2016:

- [ ] Update menu to say `Select region and distance` instead of `menu` https://github.com/dcfemtech/hackforgood-waba-map/issues/114 - wanna tackle this @hareno44? 
- [ ] Update menu to use full names instead of acronyms https://github.com/dcfemtech/hackforgood-waba-map/issues/115
- [ ] Add title to the project https://github.com/dcfemtech/hackforgood-waba-map/issues/102
- [ ] Add a description https://github.com/dcfemtech/hackforgood-waba-map/issues/103
- [ ] Add WABA logo - https://github.com/dcfemtech/hackforgood-waba-map/issues/104 ( @nellepierson just shared logo file)
- [ ] Add credit and contact line to UI - https://github.com/dcfemtech/hackforgood-waba-map/issues/106
- [ ] Re-add buffer sizes to the UI https://github.com/dcfemtech/hackforgood-waba-map/issues/108

Use @hareno44's `front-end-changes` branch to work on these - https://github.com/dcfemtech/hackforgood-waba-map/tree/front-end-changes
