### ISSUE TITLE
MVP for DCFemTech Hack For Good

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#26]
Our minimum viable product for DCFemTech Hack For Good:

- [x] Add bike lane and trail data from https://github.com/dcfemtech/hackforgood-waba-map/issues/10
- [x] Add DC bike trail data from https://github.com/dcfemtech/hackforgood-waba-map/issues/20
- [x] Fix buffering issue in https://github.com/dcfemtech/hackforgood-waba-map/issues/1
- [x] Publish latest code from `master` into `gh-pages` so it displays on https://dcfemtech.github.io/hackforgood-waba-map/

**Comment by alulsh** [comment]
For the buffering issue in https://github.com/dcfemtech/hackforgood-waba-map/issues/1, the bare minimum is to pre-generate the buffer GeoJSON and load it on browser load so that the user does not wait a long time for the dynamic generation of the buffer.

**Comment by alulsh** [comment]
Hack for Good has been over for a while. Closing.
